name: CI

on:
    push:
    pull_request:
    schedule:
        - cron: '0 0 * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ['14', '16']
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: checkout node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
            - run: npm install
            - run: npm run build
            - run: npm run cs
            - run: npm test -- --coverage --no-cache
            - run: npm run infection
              env:
                  STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
            - name: coveralls.io
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
              if: ${{ matrix.node }} == '16'
            - name: sonarcloud.io
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              if: ${{ matrix.node }} == '16'
